# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160519_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='score2',
            field=models.IntegerField(null=True),
        ),
    ]
