# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20160519_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='score2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
