# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20160520_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prono',
            name='score1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prono',
            name='score2',
            field=models.IntegerField(null=True),
        ),
    ]
