# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20160520_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='dategame',
            new_name='date_start',
        ),
    ]
