# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20160520_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(default='FRA', max_length=3),
        ),
    ]
