# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_team_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prono',
            name='score1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prono',
            name='score2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
